# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Photobook' do
  pod 'Stripe', '~> 10.1.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Photobook

  pod 'GoogleSignIn'

end
